export const QUERY_CACHE_TAGS = {
  products: 'products',
  productOptions: 'product-options',
  categories: 'categories',
  categoryOptions: 'category-options',
  warehouses: 'warehouses',
  inventory: 'inventory',
  batches: 'batches',
  expiry: 'expiry',
  reconciliation: 'reconciliation',
  stockMovements: 'stock-movements',
  stockBalances: 'stock-balances',
  stockAdjustments: 'stock-adjustments',
  stockTransfers: 'stock-transfers',
  customers: 'customers',
  customerOptions: 'customer-options',
  customerLedger: 'customer-ledger',
  receivables: 'receivables',
  suppliers: 'suppliers',
  supplierOptions: 'supplier-options',
  supplierLedger: 'supplier-ledger',
  payables: 'payables',
  returns: 'returns',
  sales: 'sales',
  purchases: 'purchases',
  expenses: 'expenses',
  expenseCategories: 'expense-categories',
  expenseCategoryOptions: 'expense-category-options',
  accounts: 'accounts',
  accountOptions: 'account-options',
  accountsSummary: 'accounts-summary',
  accountMovements: 'account-movements',
  dashboard: 'dashboard',
  reports: 'reports',
  alerts: 'alerts',
} as const;

export type QueryCacheTag = (typeof QUERY_CACHE_TAGS)[keyof typeof QUERY_CACHE_TAGS];
