// AUTO-GENERATED by scripts/generate-frontend-env.mjs — do not edit manually.
// Committed default: http://localhost:3000 (local development).
// Override by setting AGRIVIO_PUBLIC_API_BASE_URL before running the build script.
export const buildTimeApiBaseUrl = "http://localhost:3000";
